import { createFileRoute, Link } from "@tanstack/react-router";
import { Download, FileText, Lock, ShieldCheck, ShieldOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { RiskGauge } from "@/components/risk-gauge";
import { RiskBadge } from "@/components/risk-badge";
import {
  categoryCounts as demoCategoryCounts,
  demoDocument,
  detectedEntities as demoDetectedEntities,
  originalLines as demoOriginalLines,
  protectedLines as demoProtectedLines,
  recommendations as demoRecommendations,
  riskLevel as demoRiskLevel,
  riskScore as demoRiskScore,
} from "@/lib/pii-data";
import { loadScanResult } from "@/lib/scan-api";

export const Route = createFileRoute("/report")({
  head: () => ({
    meta: [
      { title: "Privacy Report — PrivX Analysis" },
      {
        name: "description",
        content:
          "PrivX Privacy Risk Analysis: detected entities, risk score, recommendations and a PrivX Safe Copy of your document.",
      },
      { property: "og:title", content: "PrivX Analysis — Privacy Report" },
      {
        property: "og:description",
        content: "Detected sensitive information, privacy risk score and PrivX Safe Copy.",
      },
      { property: "og:type", content: "article" },
      { property: "og:url", content: "https://privx.app/report" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "https://privx.app/report" }],
  }),
  component: ReportPage,
});

/** Triggers a browser download of `content` as a text file named `filename`. */
function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function safeFileStem(name: string) {
  return name.replace(/\.[^/.]+$/, "").replace(/[^a-z0-9_-]+/gi, "_");
}

/** Decodes a base64 payload and triggers a real file download (e.g. the redacted PDF/image). */
function downloadBase64File(filename: string, base64: string, mime: string) {
  const byteChars = atob(base64);
  const byteNumbers = new Array(byteChars.length);
  for (let i = 0; i < byteChars.length; i++) byteNumbers[i] = byteChars.charCodeAt(i);
  const blob = new Blob([new Uint8Array(byteNumbers)], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function ReportPage() {
  // If a real scan was just run, use it. Otherwise fall back to the
  // built-in synthetic demo data (unchanged from before).
  const scan = loadScanResult();

  const documentName = scan?.document_name ?? demoDocument.name;
  const scanDate = scan?.scan_date ?? demoDocument.scanDate;
  const riskScore = scan?.risk_score ?? demoRiskScore;
  const riskLevel = scan?.risk_level ?? demoRiskLevel;
  const categoryCounts = scan?.category_counts ?? demoCategoryCounts;
  const detectedEntities = scan?.detected_entities ?? demoDetectedEntities;
  const originalLines = scan?.original_lines ?? demoOriginalLines;
  const protectedLines = scan?.protected_lines ?? demoProtectedLines;
  const recommendations = scan?.recommendations ?? demoRecommendations;

  const stem = safeFileStem(documentName);
  const hasEntities = detectedEntities.length > 0;
  const hasCategories = Object.keys(categoryCounts).length > 0;

  const handleExportReport = () => {
    const lines: string[] = [];
    lines.push("PrivX Privacy Report");
    lines.push("=".repeat(40));
    lines.push(`Document: ${documentName}`);
    lines.push(`Scanned: ${scanDate}`);
    lines.push(`Risk score: ${riskScore} / 100 (${riskLevel})`);
    lines.push("");
    lines.push("Detected categories");
    lines.push("-".repeat(40));
    if (hasCategories) {
      for (const [cat, count] of Object.entries(categoryCounts)) {
        lines.push(`- ${cat}: ${count}`);
      }
    } else {
      lines.push("No sensitive categories detected.");
    }
    lines.push("");
    lines.push("Detected entities");
    lines.push("-".repeat(40));
    if (hasEntities) {
      for (const e of detectedEntities) {
        lines.push(`- [${e.risk}] ${e.type}: ${e.masked} (confidence ${e.confidence}%, layer: ${e.layer})`);
      }
    } else {
      lines.push("No entities detected.");
    }
    lines.push("");
    lines.push("Recommended actions");
    lines.push("-".repeat(40));
    for (const r of recommendations) {
      lines.push(`- ${r}`);
    }
    lines.push("");
    lines.push("Generated by PrivX — https://privx.app");

    downloadTextFile(`${stem}_privx_report.txt`, lines.join("\n"));
  };

  const handleDownloadSafeCopy = () => {
    downloadTextFile(`${stem}_privx_safe_copy.txt`, protectedLines.join("\n"));
  };

  const hasVisualRedaction = !!(scan?.redacted_file_base64 && scan?.redacted_file_name && scan?.redacted_file_mime);

  const handleDownloadRedactedFile = () => {
    if (!scan?.redacted_file_base64 || !scan?.redacted_file_name || !scan?.redacted_file_mime) return;
    downloadBase64File(scan.redacted_file_name, scan.redacted_file_base64, scan.redacted_file_mime);
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <span className="text-xs font-semibold tracking-widest text-ai uppercase">PrivX Analysis</span>
          <h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">Privacy Report</h1>
          <p className="mt-2 flex items-center gap-2 font-mono text-xs text-muted-foreground">
            <FileText className="h-3.5 w-3.5" /> {documentName} · {scanDate}
          </p>
        </div>
        <Button className="gradient-ai border-0 shadow-glow" onClick={handleExportReport}>
          <Download className="h-4 w-4" /> Export PrivX Report
        </Button>
      </div>

      <div className="mt-10 grid gap-6 lg:grid-cols-3">
        <div className="card-surface flex flex-col items-center p-6">
          <RiskGauge score={riskScore} />
          <RiskBadge level={riskLevel} className="mt-4" />
          <p className="mt-3 text-center text-sm text-muted-foreground">
            PrivX Privacy Risk Analysis Complete.
          </p>
        </div>

        <div className="card-surface p-6 lg:col-span-2">
          <h2 className="text-sm font-semibold">Detected categories</h2>
          {hasCategories ? (
            <div className="mt-4 grid gap-3 sm:grid-cols-2">
              {Object.entries(categoryCounts).map(([cat, count]) => (
                <div
                  key={cat}
                  className="flex items-center justify-between rounded-xl border border-border bg-card px-4 py-3"
                >
                  <span className="text-sm">{cat}</span>
                  <span className="font-display text-lg font-bold text-gradient-ai">{count}</span>
                </div>
              ))}
            </div>
          ) : (
            <div className="mt-4 flex items-center gap-3 rounded-xl border border-dashed border-border bg-secondary/30 px-4 py-6 text-sm text-muted-foreground">
              <ShieldCheck className="h-4 w-4 shrink-0 text-safe" />
              No sensitive categories were detected in this document.
            </div>
          )}
        </div>
      </div>

      <section className="mt-10">
        <h2 className="font-display text-xl font-bold">Detected entities</h2>
        {hasEntities ? (
          <div className="card-surface mt-4 overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="border-b border-border text-xs uppercase tracking-wide text-muted-foreground">
                <tr>
                  <th className="px-4 py-3">Type</th>
                  <th className="px-4 py-3">Masked value</th>
                  <th className="px-4 py-3">Detection layer</th>
                  <th className="px-4 py-3">Confidence</th>
                  <th className="px-4 py-3">Risk</th>
                </tr>
              </thead>
              <tbody>
                {detectedEntities.map((e) => (
                  <tr key={e.id} className="border-b border-border/60 last:border-0">
                    <td className="px-4 py-3 font-medium">{e.type}</td>
                    <td className="px-4 py-3 font-mono text-xs">{e.masked}</td>
                    <td className="px-4 py-3 text-muted-foreground">{e.layer}</td>
                    <td className="px-4 py-3">{e.confidence}%</td>
                    <td className="px-4 py-3">
                      <RiskBadge level={e.risk} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="card-surface mt-4 flex flex-col items-center gap-2 px-4 py-10 text-center">
            <ShieldOff className="h-6 w-6 text-muted-foreground" />
            <p className="text-sm font-medium">No sensitive entities detected</p>
            <p className="max-w-md text-xs text-muted-foreground">
              PrivX scanned this document and didn't find any recognizable PAN, Aadhaar-style, phone, email,
              bank, or named-field data. If you expected matches, try a document with clearly labeled fields
              (e.g. "Name:", "Phone:") or plain sentences mentioning a person/place/organization.
            </p>
          </div>
        )}
      </section>

      <section className="mt-10 grid gap-6 lg:grid-cols-2">
        <div className="card-surface p-6">
          <h2 className="flex items-center gap-2 text-sm font-semibold">
            <FileText className="h-4 w-4 text-muted-foreground" /> Original document
          </h2>
          <pre className="mt-4 whitespace-pre-wrap rounded-xl bg-secondary/60 p-4 font-mono text-xs">
            {originalLines.join("\n")}
          </pre>
        </div>
        <div className="card-surface p-6">
          <h2 className="flex items-center gap-2 text-sm font-semibold">
            <Lock className="h-4 w-4 text-safe" /> PrivX Safe Copy
          </h2>
          <pre className="mt-4 whitespace-pre-wrap rounded-xl bg-safe/10 p-4 font-mono text-xs">
            {protectedLines.join("\n")}
          </pre>
          <div className="mt-4 flex flex-wrap gap-2">
            {hasVisualRedaction && (
              <Button className="gradient-ai border-0 shadow-glow" onClick={handleDownloadRedactedFile}>
                <Download className="h-4 w-4" /> Download Redacted Document
              </Button>
            )}
            <Button variant="outline" onClick={handleDownloadSafeCopy}>
              <Download className="h-4 w-4" /> Download Plain Text Copy
            </Button>
          </div>
          {hasVisualRedaction && (
            <p className="mt-2 text-xs text-muted-foreground">
              The redacted document keeps the original layout — sensitive values are permanently blacked out
              in place, not just replaced with text.
            </p>
          )}
        </div>
      </section>

      <section className="mt-10">
        <h2 className="font-display text-xl font-bold">Recommended actions</h2>
        <ul className="mt-4 grid gap-3 md:grid-cols-2">
          {recommendations.map((r) => (
            <li key={r} className="card-surface flex items-start gap-3 p-4 text-sm">
              <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-ai" />
              {r}
            </li>
          ))}
        </ul>
        <div className="mt-8">
          <Button asChild variant="outline">
            <Link to="/dashboard">Back to PrivX Dashboard</Link>
          </Button>
        </div>
      </section>
    </div>
  );
}